"use client";
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 resources/ks1-model.glb -o src/app/assets/ks1-model.tsx -t -k 
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF, PerspectiveCamera } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    SOLID001_2: THREE.Mesh;
    SOLID001_3: THREE.Mesh;
    SOLID001_4: THREE.Mesh;
    SOLID001001_1: THREE.Mesh;
    SOLID001001_2: THREE.Mesh;
    SOLID001001_3: THREE.Mesh;
    SOLID001002_1: THREE.Mesh;
    SOLID001002_2: THREE.Mesh;
    SOLID001002_3: THREE.Mesh;
    SOLID001003_1: THREE.Mesh;
    SOLID001003_2: THREE.Mesh;
    SOLID001003_3: THREE.Mesh;
    SOLID001004_1: THREE.Mesh;
    SOLID001004_2: THREE.Mesh;
    SOLID001004_3: THREE.Mesh;
    SOLID001005_1: THREE.Mesh;
    SOLID001005_2: THREE.Mesh;
    SOLID001005_3: THREE.Mesh;
    SOLID001006_1: THREE.Mesh;
    SOLID001006_2: THREE.Mesh;
    SOLID001006_3: THREE.Mesh;
    SOLID001007_1: THREE.Mesh;
    SOLID001007_2: THREE.Mesh;
    SOLID001007_3: THREE.Mesh;
    SOLID001008_1: THREE.Mesh;
    SOLID001008_2: THREE.Mesh;
    SOLID001008_3: THREE.Mesh;
    SOLID001009_1: THREE.Mesh;
    SOLID001009_2: THREE.Mesh;
    SOLID001009_3: THREE.Mesh;
    SOLID001010_1: THREE.Mesh;
    SOLID001010_2: THREE.Mesh;
    SOLID001010_3: THREE.Mesh;
    SOLID001011_1: THREE.Mesh;
    SOLID001011_2: THREE.Mesh;
    SOLID001011_3: THREE.Mesh;
    SOLID001012_1: THREE.Mesh;
    SOLID001012_2: THREE.Mesh;
    SOLID001012_3: THREE.Mesh;
    SOLID001013_1: THREE.Mesh;
    SOLID001013_2: THREE.Mesh;
    SOLID001013_3: THREE.Mesh;
    SOLID001014_1: THREE.Mesh;
    SOLID001014_2: THREE.Mesh;
    SOLID001014_3: THREE.Mesh;
    SOLID001015_1: THREE.Mesh;
    SOLID001015_2: THREE.Mesh;
    SOLID001015_3: THREE.Mesh;
    SOLID001016_1: THREE.Mesh;
    SOLID001016_2: THREE.Mesh;
    SOLID001016_3: THREE.Mesh;
    SOLID001017_1: THREE.Mesh;
    SOLID001017_2: THREE.Mesh;
    SOLID001017_3: THREE.Mesh;
    SOLID001018_1: THREE.Mesh;
    SOLID001018_2: THREE.Mesh;
    SOLID001018_3: THREE.Mesh;
    SOLID001019_1: THREE.Mesh;
    SOLID001019_2: THREE.Mesh;
    SOLID001019_3: THREE.Mesh;
    SOLID001020_1: THREE.Mesh;
    SOLID001020_2: THREE.Mesh;
    SOLID001020_3: THREE.Mesh;
    COMPOUND001_2: THREE.Mesh;
    COMPOUND001_3: THREE.Mesh;
    COMPOUND001_4: THREE.Mesh;
    COMPOUND001_5: THREE.Mesh;
    COMPOUND002_1: THREE.Mesh;
    COMPOUND002_2: THREE.Mesh;
    COMPOUND002_3: THREE.Mesh;
    COMPOUND002_4: THREE.Mesh;
    COMPOUND003_1: THREE.Mesh;
    COMPOUND003_2: THREE.Mesh;
    COMPOUND003_3: THREE.Mesh;
    COMPOUND003_4: THREE.Mesh;
    COMPOUND004_1: THREE.Mesh;
    COMPOUND004_2: THREE.Mesh;
    COMPOUND004_3: THREE.Mesh;
    COMPOUND004_4: THREE.Mesh;
    COMPOUND005_1: THREE.Mesh;
    COMPOUND005_2: THREE.Mesh;
    COMPOUND005_3: THREE.Mesh;
    COMPOUND005_4: THREE.Mesh;
    COMPOUND006_1: THREE.Mesh;
    COMPOUND006_2: THREE.Mesh;
    COMPOUND006_3: THREE.Mesh;
    COMPOUND006_4: THREE.Mesh;
    COMPOUND007_1: THREE.Mesh;
    COMPOUND007_2: THREE.Mesh;
    COMPOUND007_3: THREE.Mesh;
    COMPOUND007_4: THREE.Mesh;
    COMPOUND008_1: THREE.Mesh;
    COMPOUND008_2: THREE.Mesh;
    COMPOUND008_3: THREE.Mesh;
    COMPOUND008_4: THREE.Mesh;
    COMPOUND009_1: THREE.Mesh;
    COMPOUND009_2: THREE.Mesh;
    COMPOUND009_3: THREE.Mesh;
    COMPOUND009_4: THREE.Mesh;
    COMPOUND010_1: THREE.Mesh;
    COMPOUND010_2: THREE.Mesh;
    COMPOUND010_3: THREE.Mesh;
    COMPOUND010_4: THREE.Mesh;
    COMPOUND011_1: THREE.Mesh;
    COMPOUND011_2: THREE.Mesh;
    COMPOUND011_3: THREE.Mesh;
    COMPOUND011_4: THREE.Mesh;
    COMPOUND012_1: THREE.Mesh;
    COMPOUND012_2: THREE.Mesh;
    COMPOUND012_3: THREE.Mesh;
    COMPOUND012_4: THREE.Mesh;
    COMPOUND013_1: THREE.Mesh;
    COMPOUND013_2: THREE.Mesh;
    COMPOUND013_3: THREE.Mesh;
    COMPOUND013_4: THREE.Mesh;
    COMPOUND014_1: THREE.Mesh;
    COMPOUND014_2: THREE.Mesh;
    COMPOUND014_3: THREE.Mesh;
    COMPOUND014_4: THREE.Mesh;
    COMPOUND015_1: THREE.Mesh;
    COMPOUND015_2: THREE.Mesh;
    COMPOUND015_3: THREE.Mesh;
    COMPOUND015_4: THREE.Mesh;
    COMPOUND016_1: THREE.Mesh;
    COMPOUND016_2: THREE.Mesh;
    COMPOUND016_3: THREE.Mesh;
    COMPOUND016_4: THREE.Mesh;
    COMPOUND017_1: THREE.Mesh;
    COMPOUND017_2: THREE.Mesh;
    COMPOUND017_3: THREE.Mesh;
    COMPOUND017_4: THREE.Mesh;
    COMPOUND018_1: THREE.Mesh;
    COMPOUND018_2: THREE.Mesh;
    COMPOUND018_3: THREE.Mesh;
    COMPOUND018_4: THREE.Mesh;
    COMPOUND019_1: THREE.Mesh;
    COMPOUND019_2: THREE.Mesh;
    COMPOUND019_3: THREE.Mesh;
    COMPOUND019_4: THREE.Mesh;
    COMPOUND020_1: THREE.Mesh;
    COMPOUND020_2: THREE.Mesh;
    COMPOUND020_3: THREE.Mesh;
    COMPOUND020_4: THREE.Mesh;
    COMPOUND_1: THREE.Mesh;
    COMPOUND_2: THREE.Mesh;
    COMPOUND_3: THREE.Mesh;
    COMPOUND_4: THREE.Mesh;
    SOLID002: THREE.Mesh;
    COMPOUND001_6: THREE.Mesh;
    COMPOUND001_7: THREE.Mesh;
    COMPOUND001_8: THREE.Mesh;
    COMPOUND001_9: THREE.Mesh;
    COMPOUND001_10: THREE.Mesh;
    COMPOUND001_11: THREE.Mesh;
    COMPOUND001_12: THREE.Mesh;
    COMPOUND001_13: THREE.Mesh;
    COMPOUND001_14: THREE.Mesh;
    COMPOUND001_15: THREE.Mesh;
    COMPOUND001_16: THREE.Mesh;
    COMPOUND001_17: THREE.Mesh;
    SOLID_1: THREE.Mesh;
    SOLID_2: THREE.Mesh;
    SOLID_3: THREE.Mesh;
    SOLID_4: THREE.Mesh;
    SOLID_5: THREE.Mesh;
    SOLID_6: THREE.Mesh;
    SOLID001_5: THREE.Mesh;
    SOLID001_6: THREE.Mesh;
    SOLID001_7: THREE.Mesh;
    SOLID001_8: THREE.Mesh;
    SOLID001_9: THREE.Mesh;
    SOLID001_10: THREE.Mesh;
    SOLID002_3: THREE.Mesh;
    SOLID002_4: THREE.Mesh;
    SOLID002_5: THREE.Mesh;
    SOLID002_6: THREE.Mesh;
    SOLID002_7: THREE.Mesh;
    SOLID002_8: THREE.Mesh;
    SOLID003_1: THREE.Mesh;
    SOLID003_2: THREE.Mesh;
    SOLID003_3: THREE.Mesh;
    SOLID003_4: THREE.Mesh;
    SOLID003_5: THREE.Mesh;
    SOLID003_6: THREE.Mesh;
    SOLID004_1: THREE.Mesh;
    SOLID004_2: THREE.Mesh;
    SOLID004_3: THREE.Mesh;
    SOLID004_4: THREE.Mesh;
    SOLID004_5: THREE.Mesh;
    SOLID004_6: THREE.Mesh;
    SOLID005_1: THREE.Mesh;
    SOLID005_2: THREE.Mesh;
    SOLID005_3: THREE.Mesh;
    SOLID005_4: THREE.Mesh;
    SOLID005_5: THREE.Mesh;
    SOLID005_6: THREE.Mesh;
    SOLID006_1: THREE.Mesh;
    SOLID006_2: THREE.Mesh;
    SOLID006_3: THREE.Mesh;
    SOLID006_4: THREE.Mesh;
    SOLID006_5: THREE.Mesh;
    SOLID006_6: THREE.Mesh;
    SOLID007_1: THREE.Mesh;
    SOLID007_2: THREE.Mesh;
    SOLID007_3: THREE.Mesh;
    SOLID007_4: THREE.Mesh;
    SOLID007_5: THREE.Mesh;
    SOLID007_6: THREE.Mesh;
    SOLID008_1: THREE.Mesh;
    SOLID008_2: THREE.Mesh;
    SOLID008_3: THREE.Mesh;
    SOLID008_4: THREE.Mesh;
    SOLID008_5: THREE.Mesh;
    SOLID008_6: THREE.Mesh;
    SOLID009_1: THREE.Mesh;
    SOLID009_2: THREE.Mesh;
    SOLID009_3: THREE.Mesh;
    SOLID009_4: THREE.Mesh;
    SOLID009_5: THREE.Mesh;
    SOLID009_6: THREE.Mesh;
    SOLID010_1: THREE.Mesh;
    SOLID010_2: THREE.Mesh;
    SOLID010_3: THREE.Mesh;
    SOLID010_4: THREE.Mesh;
    SOLID010_5: THREE.Mesh;
    SOLID010_6: THREE.Mesh;
    SOLID011_1: THREE.Mesh;
    SOLID011_2: THREE.Mesh;
    SOLID011_3: THREE.Mesh;
    SOLID011_4: THREE.Mesh;
    SOLID011_5: THREE.Mesh;
    SOLID011_6: THREE.Mesh;
    SOLID012_1: THREE.Mesh;
    SOLID012_2: THREE.Mesh;
    SOLID012_3: THREE.Mesh;
    SOLID012_4: THREE.Mesh;
    SOLID012_5: THREE.Mesh;
    SOLID012_6: THREE.Mesh;
    SOLID013_1: THREE.Mesh;
    SOLID013_2: THREE.Mesh;
    SOLID013_3: THREE.Mesh;
    SOLID013_4: THREE.Mesh;
    SOLID013_5: THREE.Mesh;
    SOLID013_6: THREE.Mesh;
    SOLID014_1: THREE.Mesh;
    SOLID014_2: THREE.Mesh;
    SOLID014_3: THREE.Mesh;
    SOLID014_4: THREE.Mesh;
    SOLID014_5: THREE.Mesh;
    SOLID014_6: THREE.Mesh;
    SOLID015_1: THREE.Mesh;
    SOLID015_2: THREE.Mesh;
    SOLID015_3: THREE.Mesh;
    SOLID015_4: THREE.Mesh;
    SOLID015_5: THREE.Mesh;
    SOLID015_6: THREE.Mesh;
    SOLID016_1: THREE.Mesh;
    SOLID016_2: THREE.Mesh;
    SOLID016_3: THREE.Mesh;
    SOLID016_4: THREE.Mesh;
    SOLID016_5: THREE.Mesh;
    SOLID016_6: THREE.Mesh;
    SOLID017_1: THREE.Mesh;
    SOLID017_2: THREE.Mesh;
    SOLID017_3: THREE.Mesh;
    SOLID017_4: THREE.Mesh;
    SOLID017_5: THREE.Mesh;
    SOLID017_6: THREE.Mesh;
    SOLID018_1: THREE.Mesh;
    SOLID018_2: THREE.Mesh;
    SOLID018_3: THREE.Mesh;
    SOLID018_4: THREE.Mesh;
    SOLID018_5: THREE.Mesh;
    SOLID018_6: THREE.Mesh;
    SOLID019_1: THREE.Mesh;
    SOLID019_2: THREE.Mesh;
    SOLID019_3: THREE.Mesh;
    SOLID019_4: THREE.Mesh;
    SOLID019_5: THREE.Mesh;
    SOLID019_6: THREE.Mesh;
    SOLID020_1: THREE.Mesh;
    SOLID020_2: THREE.Mesh;
    SOLID020_3: THREE.Mesh;
    SOLID020_4: THREE.Mesh;
    SOLID020_5: THREE.Mesh;
    SOLID020_6: THREE.Mesh;
    v1_PCB: THREE.Mesh;
    ["case-top"]: THREE.Mesh;
    keycap001: THREE.Mesh;
    keycap002: THREE.Mesh;
    keycap003: THREE.Mesh;
    keycap004: THREE.Mesh;
    keycap005: THREE.Mesh;
    keycap006: THREE.Mesh;
    keycap007: THREE.Mesh;
    keycap008: THREE.Mesh;
    keycap009: THREE.Mesh;
    keycap010: THREE.Mesh;
    keycap011: THREE.Mesh;
    keycap012: THREE.Mesh;
    keycap013: THREE.Mesh;
    keycap014: THREE.Mesh;
    keycap015: THREE.Mesh;
    keycap016: THREE.Mesh;
    keycap017: THREE.Mesh;
    keycap018: THREE.Mesh;
    keycap019: THREE.Mesh;
    keycap020: THREE.Mesh;
    keycap: THREE.Mesh;
  };
  materials: {
    mat_10: THREE.MeshStandardMaterial;
    mat_11: THREE.MeshStandardMaterial;
    mat_12: THREE.MeshStandardMaterial;
    mat_0: THREE.MeshStandardMaterial;
    mat_1: THREE.MeshStandardMaterial;
    mat_2: THREE.MeshStandardMaterial;
    mat_3: THREE.MeshStandardMaterial;
    plate: THREE.MeshStandardMaterial;
    mat_13: THREE.MeshStandardMaterial;
    mat_14: THREE.MeshStandardMaterial;
    mat_15: THREE.MeshStandardMaterial;
    mat_16: THREE.MeshStandardMaterial;
    mat_17: THREE.MeshStandardMaterial;
    mat_18: THREE.MeshStandardMaterial;
    mat_19: THREE.MeshStandardMaterial;
    mat_20: THREE.MeshStandardMaterial;
    mat_21: THREE.MeshStandardMaterial;
    mat_22: THREE.MeshStandardMaterial;
    mat_23: THREE.MeshStandardMaterial;
    mat_4: THREE.MeshStandardMaterial;
    mat_5: THREE.MeshStandardMaterial;
    mat_6: THREE.MeshStandardMaterial;
    mat_7: THREE.MeshStandardMaterial;
    mat_8: THREE.MeshStandardMaterial;
    mat_9: THREE.MeshStandardMaterial;
    mat_24: THREE.MeshStandardMaterial;
  };
};

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements["mesh"]>
>;

export function KS1Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/ks1-model.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group name="pcb" position={[-0.065, 0.006, -0.037]}>
        <group
          name="Diode_SOD-123"
          position={[0.064, 0, 0.024]}
          rotation={[Math.PI, Math.PI / 2, 0]}
        >
          <mesh
            name="SOLID001_2"
            geometry={nodes.SOLID001_2.geometry}
            material={materials.mat_10}
          />
          <mesh
            name="SOLID001_3"
            geometry={nodes.SOLID001_3.geometry}
            material={materials.mat_11}
          />
          <mesh
            name="SOLID001_4"
            geometry={nodes.SOLID001_4.geometry}
            material={materials.mat_12}
          />
        </group>
        <group
          name="Diode_SOD-124"
          position={[0.007, 0, 0.014]}
          rotation={[Math.PI, -Math.PI / 2, 0]}
        >
          <mesh
            name="SOLID001001_1"
            geometry={nodes.SOLID001001_1.geometry}
            material={materials.mat_10}
          />
          <mesh
            name="SOLID001001_2"
            geometry={nodes.SOLID001001_2.geometry}
            material={materials.mat_11}
          />
          <mesh
            name="SOLID001001_3"
            geometry={nodes.SOLID001001_3.geometry}
            material={materials.mat_12}
          />
        </group>
        <group
          name="Diode_SOD-125"
          position={[0.045, 0, 0.008]}
          rotation={[Math.PI, -Math.PI / 2, 0]}
        >
          <mesh
            name="SOLID001002_1"
            geometry={nodes.SOLID001002_1.geometry}
            material={materials.mat_10}
          />
          <mesh
            name="SOLID001002_2"
            geometry={nodes.SOLID001002_2.geometry}
            material={materials.mat_11}
          />
          <mesh
            name="SOLID001002_3"
            geometry={nodes.SOLID001002_3.geometry}
            material={materials.mat_12}
          />
        </group>
        <group
          name="Diode_SOD-126"
          position={[0.026, 0, 0.029]}
          rotation={[Math.PI, Math.PI / 2, 0]}
        >
          <mesh
            name="SOLID001003_1"
            geometry={nodes.SOLID001003_1.geometry}
            material={materials.mat_10}
          />
          <mesh
            name="SOLID001003_2"
            geometry={nodes.SOLID001003_2.geometry}
            material={materials.mat_11}
          />
          <mesh
            name="SOLID001003_3"
            geometry={nodes.SOLID001003_3.geometry}
            material={materials.mat_12}
          />
        </group>
        <group
          name="Diode_SOD-127"
          position={[0.102, 0, 0.012]}
          rotation={[Math.PI, -Math.PI / 2, 0]}
        >
          <mesh
            name="SOLID001004_1"
            geometry={nodes.SOLID001004_1.geometry}
            material={materials.mat_10}
          />
          <mesh
            name="SOLID001004_2"
            geometry={nodes.SOLID001004_2.geometry}
            material={materials.mat_11}
          />
          <mesh
            name="SOLID001004_3"
            geometry={nodes.SOLID001004_3.geometry}
            material={materials.mat_12}
          />
        </group>
        <group
          name="Diode_SOD-128"
          position={[0.053, 0, 0.042]}
          rotation={[Math.PI, Math.PI / 2, 0]}
        >
          <mesh
            name="SOLID001005_1"
            geometry={nodes.SOLID001005_1.geometry}
            material={materials.mat_10}
          />
          <mesh
            name="SOLID001005_2"
            geometry={nodes.SOLID001005_2.geometry}
            material={materials.mat_11}
          />
          <mesh
            name="SOLID001005_3"
            geometry={nodes.SOLID001005_3.geometry}
            material={materials.mat_12}
          />
        </group>
        <group
          name="Diode_SOD-129"
          position={[0.034, 0, 0.044]}
          rotation={[Math.PI, Math.PI / 2, 0]}
        >
          <mesh
            name="SOLID001006_1"
            geometry={nodes.SOLID001006_1.geometry}
            material={materials.mat_10}
          />
          <mesh
            name="SOLID001006_2"
            geometry={nodes.SOLID001006_2.geometry}
            material={materials.mat_11}
          />
          <mesh
            name="SOLID001006_3"
            geometry={nodes.SOLID001006_3.geometry}
            material={materials.mat_12}
          />
        </group>
        <group
          name="Diode_SOD-130"
          position={[0.083, 0, 0.063]}
          rotation={[Math.PI, Math.PI / 2, 0]}
        >
          <mesh
            name="SOLID001007_1"
            geometry={nodes.SOLID001007_1.geometry}
            material={materials.mat_10}
          />
          <mesh
            name="SOLID001007_2"
            geometry={nodes.SOLID001007_2.geometry}
            material={materials.mat_11}
          />
          <mesh
            name="SOLID001007_3"
            geometry={nodes.SOLID001007_3.geometry}
            material={materials.mat_12}
          />
        </group>
        <group
          name="Diode_SOD-131"
          position={[0.083, 0, 0.047]}
          rotation={[Math.PI, Math.PI / 2, 0]}
        >
          <mesh
            name="SOLID001008_1"
            geometry={nodes.SOLID001008_1.geometry}
            material={materials.mat_10}
          />
          <mesh
            name="SOLID001008_2"
            geometry={nodes.SOLID001008_2.geometry}
            material={materials.mat_11}
          />
          <mesh
            name="SOLID001008_3"
            geometry={nodes.SOLID001008_3.geometry}
            material={materials.mat_12}
          />
        </group>
        <group
          name="Diode_SOD-132"
          position={[0.083, 0, 0.011]}
          rotation={[Math.PI, -Math.PI / 2, 0]}
        >
          <mesh
            name="SOLID001009_1"
            geometry={nodes.SOLID001009_1.geometry}
            material={materials.mat_10}
          />
          <mesh
            name="SOLID001009_2"
            geometry={nodes.SOLID001009_2.geometry}
            material={materials.mat_11}
          />
          <mesh
            name="SOLID001009_3"
            geometry={nodes.SOLID001009_3.geometry}
            material={materials.mat_12}
          />
        </group>
        <group
          name="Diode_SOD-133"
          position={[0.015, 0, 0.048]}
          rotation={[Math.PI, Math.PI / 2, 0]}
        >
          <mesh
            name="SOLID001010_1"
            geometry={nodes.SOLID001010_1.geometry}
            material={materials.mat_10}
          />
          <mesh
            name="SOLID001010_2"
            geometry={nodes.SOLID001010_2.geometry}
            material={materials.mat_11}
          />
          <mesh
            name="SOLID001010_3"
            geometry={nodes.SOLID001010_3.geometry}
            material={materials.mat_12}
          />
        </group>
        <group
          name="Diode_SOD-134"
          position={[0.064, 0, 0.006]}
          rotation={[Math.PI, -Math.PI / 2, 0]}
        >
          <mesh
            name="SOLID001011_1"
            geometry={nodes.SOLID001011_1.geometry}
            material={materials.mat_10}
          />
          <mesh
            name="SOLID001011_2"
            geometry={nodes.SOLID001011_2.geometry}
            material={materials.mat_11}
          />
          <mesh
            name="SOLID001011_3"
            geometry={nodes.SOLID001011_3.geometry}
            material={materials.mat_12}
          />
        </group>
        <group
          name="Diode_SOD-135"
          position={[0.1, 0, 0.033]}
          rotation={[Math.PI, 0, 0]}
        >
          <mesh
            name="SOLID001012_1"
            geometry={nodes.SOLID001012_1.geometry}
            material={materials.mat_10}
          />
          <mesh
            name="SOLID001012_2"
            geometry={nodes.SOLID001012_2.geometry}
            material={materials.mat_11}
          />
          <mesh
            name="SOLID001012_3"
            geometry={nodes.SOLID001012_3.geometry}
            material={materials.mat_12}
          />
        </group>
        <group
          name="Diode_SOD-136"
          position={[0.106, 0, 0.067]}
          rotation={[Math.PI, Math.PI / 2, 0]}
        >
          <mesh
            name="SOLID001013_1"
            geometry={nodes.SOLID001013_1.geometry}
            material={materials.mat_10}
          />
          <mesh
            name="SOLID001013_2"
            geometry={nodes.SOLID001013_2.geometry}
            material={materials.mat_11}
          />
          <mesh
            name="SOLID001013_3"
            geometry={nodes.SOLID001013_3.geometry}
            material={materials.mat_12}
          />
        </group>
        <group
          name="Diode_SOD-137"
          position={[0.07, 0, 0.042]}
          rotation={[Math.PI, Math.PI / 2, 0]}
        >
          <mesh
            name="SOLID001014_1"
            geometry={nodes.SOLID001014_1.geometry}
            material={materials.mat_10}
          />
          <mesh
            name="SOLID001014_2"
            geometry={nodes.SOLID001014_2.geometry}
            material={materials.mat_11}
          />
          <mesh
            name="SOLID001014_3"
            geometry={nodes.SOLID001014_3.geometry}
            material={materials.mat_12}
          />
        </group>
        <group
          name="Diode_SOD-138"
          position={[0.083, 0, 0.028]}
          rotation={[Math.PI, Math.PI / 2, 0]}
        >
          <mesh
            name="SOLID001015_1"
            geometry={nodes.SOLID001015_1.geometry}
            material={materials.mat_10}
          />
          <mesh
            name="SOLID001015_2"
            geometry={nodes.SOLID001015_2.geometry}
            material={materials.mat_11}
          />
          <mesh
            name="SOLID001015_3"
            geometry={nodes.SOLID001015_3.geometry}
            material={materials.mat_12}
          />
        </group>
        <group
          name="Diode_SOD-139"
          position={[0.007, 0, 0.031]}
          rotation={[Math.PI, Math.PI / 2, 0]}
        >
          <mesh
            name="SOLID001016_1"
            geometry={nodes.SOLID001016_1.geometry}
            material={materials.mat_10}
          />
          <mesh
            name="SOLID001016_2"
            geometry={nodes.SOLID001016_2.geometry}
            material={materials.mat_11}
          />
          <mesh
            name="SOLID001016_3"
            geometry={nodes.SOLID001016_3.geometry}
            material={materials.mat_12}
          />
        </group>
        <group
          name="Diode_SOD-140"
          position={[0.045, 0, 0.026]}
          rotation={[Math.PI, Math.PI / 2, 0]}
        >
          <mesh
            name="SOLID001017_1"
            geometry={nodes.SOLID001017_1.geometry}
            material={materials.mat_10}
          />
          <mesh
            name="SOLID001017_2"
            geometry={nodes.SOLID001017_2.geometry}
            material={materials.mat_11}
          />
          <mesh
            name="SOLID001017_3"
            geometry={nodes.SOLID001017_3.geometry}
            material={materials.mat_12}
          />
        </group>
        <group
          name="Diode_SOD-141"
          position={[0.026, 0, 0.012]}
          rotation={[Math.PI, -Math.PI / 2, 0]}
        >
          <mesh
            name="SOLID001018_1"
            geometry={nodes.SOLID001018_1.geometry}
            material={materials.mat_10}
          />
          <mesh
            name="SOLID001018_2"
            geometry={nodes.SOLID001018_2.geometry}
            material={materials.mat_11}
          />
          <mesh
            name="SOLID001018_3"
            geometry={nodes.SOLID001018_3.geometry}
            material={materials.mat_12}
          />
        </group>
        <group
          name="Diode_SOD-142"
          position={[0.103, 0, 0.067]}
          rotation={[Math.PI, Math.PI / 2, 0]}
        >
          <mesh
            name="SOLID001019_1"
            geometry={nodes.SOLID001019_1.geometry}
            material={materials.mat_10}
          />
          <mesh
            name="SOLID001019_2"
            geometry={nodes.SOLID001019_2.geometry}
            material={materials.mat_11}
          />
          <mesh
            name="SOLID001019_3"
            geometry={nodes.SOLID001019_3.geometry}
            material={materials.mat_12}
          />
        </group>
        <group
          name="Diode_SOD-143"
          position={[0.102, 0, 0.049]}
          rotation={[Math.PI, Math.PI / 2, 0]}
        >
          <mesh
            name="SOLID001020_1"
            geometry={nodes.SOLID001020_1.geometry}
            material={materials.mat_10}
          />
          <mesh
            name="SOLID001020_2"
            geometry={nodes.SOLID001020_2.geometry}
            material={materials.mat_11}
          />
          <mesh
            name="SOLID001020_3"
            geometry={nodes.SOLID001020_3.geometry}
            material={materials.mat_12}
          />
        </group>
        <group name="gateron-ks034" position={[0.102, 0.002, 0.005]}>
          <mesh
            name="COMPOUND001_2"
            geometry={nodes.COMPOUND001_2.geometry}
            material={materials.mat_0}
          />
          <mesh
            name="COMPOUND001_3"
            geometry={nodes.COMPOUND001_3.geometry}
            material={materials.mat_1}
          />
          <mesh
            name="COMPOUND001_4"
            geometry={nodes.COMPOUND001_4.geometry}
            material={materials.mat_2}
          />
          <mesh
            name="COMPOUND001_5"
            geometry={nodes.COMPOUND001_5.geometry}
            material={materials.mat_3}
          />
        </group>
        <group name="gateron-ks035" position={[0.064, 0.002, 0.037]}>
          <mesh
            name="COMPOUND002_1"
            geometry={nodes.COMPOUND002_1.geometry}
            material={materials.mat_0}
          />
          <mesh
            name="COMPOUND002_2"
            geometry={nodes.COMPOUND002_2.geometry}
            material={materials.mat_1}
          />
          <mesh
            name="COMPOUND002_3"
            geometry={nodes.COMPOUND002_3.geometry}
            material={materials.mat_2}
          />
          <mesh
            name="COMPOUND002_4"
            geometry={nodes.COMPOUND002_4.geometry}
            material={materials.mat_3}
          />
        </group>
        <group name="gateron-ks036" position={[0.007, 0.002, 0.026]}>
          <mesh
            name="COMPOUND003_1"
            geometry={nodes.COMPOUND003_1.geometry}
            material={materials.mat_0}
          />
          <mesh
            name="COMPOUND003_2"
            geometry={nodes.COMPOUND003_2.geometry}
            material={materials.mat_1}
          />
          <mesh
            name="COMPOUND003_3"
            geometry={nodes.COMPOUND003_3.geometry}
            material={materials.mat_2}
          />
          <mesh
            name="COMPOUND003_4"
            geometry={nodes.COMPOUND003_4.geometry}
            material={materials.mat_3}
          />
        </group>
        <group name="gateron-ks037" position={[0.102, 0.002, 0.024]}>
          <mesh
            name="COMPOUND004_1"
            geometry={nodes.COMPOUND004_1.geometry}
            material={materials.mat_0}
          />
          <mesh
            name="COMPOUND004_2"
            geometry={nodes.COMPOUND004_2.geometry}
            material={materials.mat_1}
          />
          <mesh
            name="COMPOUND004_3"
            geometry={nodes.COMPOUND004_3.geometry}
            material={materials.mat_2}
          />
          <mesh
            name="COMPOUND004_4"
            geometry={nodes.COMPOUND004_4.geometry}
            material={materials.mat_3}
          />
        </group>
        <group name="gateron-ks038" position={[0.007, 0.002, 0.007]}>
          <mesh
            name="COMPOUND005_1"
            geometry={nodes.COMPOUND005_1.geometry}
            material={materials.mat_0}
          />
          <mesh
            name="COMPOUND005_2"
            geometry={nodes.COMPOUND005_2.geometry}
            material={materials.mat_1}
          />
          <mesh
            name="COMPOUND005_3"
            geometry={nodes.COMPOUND005_3.geometry}
            material={materials.mat_2}
          />
          <mesh
            name="COMPOUND005_4"
            geometry={nodes.COMPOUND005_4.geometry}
            material={materials.mat_3}
          />
        </group>
        <group name="gateron-ks039" position={[0.064, 0.002, -0.001]}>
          <mesh
            name="COMPOUND006_1"
            geometry={nodes.COMPOUND006_1.geometry}
            material={materials.mat_0}
          />
          <mesh
            name="COMPOUND006_2"
            geometry={nodes.COMPOUND006_2.geometry}
            material={materials.mat_1}
          />
          <mesh
            name="COMPOUND006_3"
            geometry={nodes.COMPOUND006_3.geometry}
            material={materials.mat_2}
          />
          <mesh
            name="COMPOUND006_4"
            geometry={nodes.COMPOUND006_4.geometry}
            material={materials.mat_3}
          />
        </group>
        <group name="gateron-ks040" position={[0.083, 0.002, 0.022]}>
          <mesh
            name="COMPOUND007_1"
            geometry={nodes.COMPOUND007_1.geometry}
            material={materials.mat_0}
          />
          <mesh
            name="COMPOUND007_2"
            geometry={nodes.COMPOUND007_2.geometry}
            material={materials.mat_1}
          />
          <mesh
            name="COMPOUND007_3"
            geometry={nodes.COMPOUND007_3.geometry}
            material={materials.mat_2}
          />
          <mesh
            name="COMPOUND007_4"
            geometry={nodes.COMPOUND007_4.geometry}
            material={materials.mat_3}
          />
        </group>
        <group
          name="gateron-ks041"
          position={[0.114, 0.002, 0.068]}
          rotation={[0, -0.262, 0]}
        >
          <mesh
            name="COMPOUND008_1"
            geometry={nodes.COMPOUND008_1.geometry}
            material={materials.mat_0}
          />
          <mesh
            name="COMPOUND008_2"
            geometry={nodes.COMPOUND008_2.geometry}
            material={materials.mat_1}
          />
          <mesh
            name="COMPOUND008_3"
            geometry={nodes.COMPOUND008_3.geometry}
            material={materials.mat_2}
          />
          <mesh
            name="COMPOUND008_4"
            geometry={nodes.COMPOUND008_4.geometry}
            material={materials.mat_3}
          />
        </group>
        <group name="gateron-ks042" position={[0.026, 0.002, 0.043]}>
          <mesh
            name="COMPOUND009_1"
            geometry={nodes.COMPOUND009_1.geometry}
            material={materials.mat_0}
          />
          <mesh
            name="COMPOUND009_2"
            geometry={nodes.COMPOUND009_2.geometry}
            material={materials.mat_1}
          />
          <mesh
            name="COMPOUND009_3"
            geometry={nodes.COMPOUND009_3.geometry}
            material={materials.mat_2}
          />
          <mesh
            name="COMPOUND009_4"
            geometry={nodes.COMPOUND009_4.geometry}
            material={materials.mat_3}
          />
        </group>
        <group name="gateron-ks043" position={[0.064, 0.002, 0.018]}>
          <mesh
            name="COMPOUND010_1"
            geometry={nodes.COMPOUND010_1.geometry}
            material={materials.mat_0}
          />
          <mesh
            name="COMPOUND010_2"
            geometry={nodes.COMPOUND010_2.geometry}
            material={materials.mat_1}
          />
          <mesh
            name="COMPOUND010_3"
            geometry={nodes.COMPOUND010_3.geometry}
            material={materials.mat_2}
          />
          <mesh
            name="COMPOUND010_4"
            geometry={nodes.COMPOUND010_4.geometry}
            material={materials.mat_3}
          />
        </group>
        <group name="gateron-ks044" position={[0.045, 0.002, 0.001]}>
          <mesh
            name="COMPOUND011_1"
            geometry={nodes.COMPOUND011_1.geometry}
            material={materials.mat_0}
          />
          <mesh
            name="COMPOUND011_2"
            geometry={nodes.COMPOUND011_2.geometry}
            material={materials.mat_1}
          />
          <mesh
            name="COMPOUND011_3"
            geometry={nodes.COMPOUND011_3.geometry}
            material={materials.mat_2}
          />
          <mesh
            name="COMPOUND011_4"
            geometry={nodes.COMPOUND011_4.geometry}
            material={materials.mat_3}
          />
        </group>
        <group name="gateron-ks045" position={[0.007, 0.002, 0.045]}>
          <mesh
            name="COMPOUND012_1"
            geometry={nodes.COMPOUND012_1.geometry}
            material={materials.mat_0}
          />
          <mesh
            name="COMPOUND012_2"
            geometry={nodes.COMPOUND012_2.geometry}
            material={materials.mat_1}
          />
          <mesh
            name="COMPOUND012_3"
            geometry={nodes.COMPOUND012_3.geometry}
            material={materials.mat_2}
          />
          <mesh
            name="COMPOUND012_4"
            geometry={nodes.COMPOUND012_4.geometry}
            material={materials.mat_3}
          />
        </group>
        <group name="gateron-ks046" position={[0.026, 0.002, 0.024]}>
          <mesh
            name="COMPOUND013_1"
            geometry={nodes.COMPOUND013_1.geometry}
            material={materials.mat_0}
          />
          <mesh
            name="COMPOUND013_2"
            geometry={nodes.COMPOUND013_2.geometry}
            material={materials.mat_1}
          />
          <mesh
            name="COMPOUND013_3"
            geometry={nodes.COMPOUND013_3.geometry}
            material={materials.mat_2}
          />
          <mesh
            name="COMPOUND013_4"
            geometry={nodes.COMPOUND013_4.geometry}
            material={materials.mat_3}
          />
        </group>
        <group
          name="gateron-ks047"
          position={[0.094, 0.002, 0.062]}
          rotation={[0, -0.087, 0]}
        >
          <mesh
            name="COMPOUND014_1"
            geometry={nodes.COMPOUND014_1.geometry}
            material={materials.mat_0}
          />
          <mesh
            name="COMPOUND014_2"
            geometry={nodes.COMPOUND014_2.geometry}
            material={materials.mat_1}
          />
          <mesh
            name="COMPOUND014_3"
            geometry={nodes.COMPOUND014_3.geometry}
            material={materials.mat_2}
          />
          <mesh
            name="COMPOUND014_4"
            geometry={nodes.COMPOUND014_4.geometry}
            material={materials.mat_3}
          />
        </group>
        <group name="gateron-ks048" position={[0.083, 0.002, 0.003]}>
          <mesh
            name="COMPOUND015_1"
            geometry={nodes.COMPOUND015_1.geometry}
            material={materials.mat_0}
          />
          <mesh
            name="COMPOUND015_2"
            geometry={nodes.COMPOUND015_2.geometry}
            material={materials.mat_1}
          />
          <mesh
            name="COMPOUND015_3"
            geometry={nodes.COMPOUND015_3.geometry}
            material={materials.mat_2}
          />
          <mesh
            name="COMPOUND015_4"
            geometry={nodes.COMPOUND015_4.geometry}
            material={materials.mat_3}
          />
        </group>
        <group name="gateron-ks049" position={[0.074, 0.002, 0.059]}>
          <mesh
            name="COMPOUND016_1"
            geometry={nodes.COMPOUND016_1.geometry}
            material={materials.mat_0}
          />
          <mesh
            name="COMPOUND016_2"
            geometry={nodes.COMPOUND016_2.geometry}
            material={materials.mat_1}
          />
          <mesh
            name="COMPOUND016_3"
            geometry={nodes.COMPOUND016_3.geometry}
            material={materials.mat_2}
          />
          <mesh
            name="COMPOUND016_4"
            geometry={nodes.COMPOUND016_4.geometry}
            material={materials.mat_3}
          />
        </group>
        <group name="gateron-ks050" position={[0.045, 0.002, 0.02]}>
          <mesh
            name="COMPOUND017_1"
            geometry={nodes.COMPOUND017_1.geometry}
            material={materials.mat_0}
          />
          <mesh
            name="COMPOUND017_2"
            geometry={nodes.COMPOUND017_2.geometry}
            material={materials.mat_1}
          />
          <mesh
            name="COMPOUND017_3"
            geometry={nodes.COMPOUND017_3.geometry}
            material={materials.mat_2}
          />
          <mesh
            name="COMPOUND017_4"
            geometry={nodes.COMPOUND017_4.geometry}
            material={materials.mat_3}
          />
        </group>
        <group name="gateron-ks051" position={[0.083, 0.002, 0.041]}>
          <mesh
            name="COMPOUND018_1"
            geometry={nodes.COMPOUND018_1.geometry}
            material={materials.mat_0}
          />
          <mesh
            name="COMPOUND018_2"
            geometry={nodes.COMPOUND018_2.geometry}
            material={materials.mat_1}
          />
          <mesh
            name="COMPOUND018_3"
            geometry={nodes.COMPOUND018_3.geometry}
            material={materials.mat_2}
          />
          <mesh
            name="COMPOUND018_4"
            geometry={nodes.COMPOUND018_4.geometry}
            material={materials.mat_3}
          />
        </group>
        <group name="gateron-ks052" position={[0.045, 0.002, 0.039]}>
          <mesh
            name="COMPOUND019_1"
            geometry={nodes.COMPOUND019_1.geometry}
            material={materials.mat_0}
          />
          <mesh
            name="COMPOUND019_2"
            geometry={nodes.COMPOUND019_2.geometry}
            material={materials.mat_1}
          />
          <mesh
            name="COMPOUND019_3"
            geometry={nodes.COMPOUND019_3.geometry}
            material={materials.mat_2}
          />
          <mesh
            name="COMPOUND019_4"
            geometry={nodes.COMPOUND019_4.geometry}
            material={materials.mat_3}
          />
        </group>
        <group name="gateron-ks053" position={[0.102, 0.002, 0.043]}>
          <mesh
            name="COMPOUND020_1"
            geometry={nodes.COMPOUND020_1.geometry}
            material={materials.mat_0}
          />
          <mesh
            name="COMPOUND020_2"
            geometry={nodes.COMPOUND020_2.geometry}
            material={materials.plate}
          />
          <mesh
            name="COMPOUND020_3"
            geometry={nodes.COMPOUND020_3.geometry}
            material={materials.mat_2}
          />
          <mesh
            name="COMPOUND020_4"
            geometry={nodes.COMPOUND020_4.geometry}
            material={materials.mat_3}
          />
        </group>
        <group name="gateron-ks33" position={[0.026, 0.002, 0.005]}>
          <mesh
            name="COMPOUND_1"
            geometry={nodes.COMPOUND_1.geometry}
            material={materials.mat_0}
          />
          <mesh
            name="COMPOUND_2"
            geometry={nodes.COMPOUND_2.geometry}
            material={materials.mat_1}
          />
          <mesh
            name="COMPOUND_3"
            geometry={nodes.COMPOUND_3.geometry}
            material={materials.mat_2}
          />
          <mesh
            name="COMPOUND_4"
            geometry={nodes.COMPOUND_4.geometry}
            material={materials.mat_3}
          />
        </group>
        <group
          name="pro-micro"
          position={[0.1, 0.002, 0.016]}
          rotation={[-Math.PI, Math.PI / 2, 0]}
        >
          <mesh
            name="COMPOUND001_6"
            geometry={nodes.COMPOUND001_6.geometry}
            material={materials.mat_13}
          />
          <mesh
            name="COMPOUND001_7"
            geometry={nodes.COMPOUND001_7.geometry}
            material={materials.mat_3}
          />
          <mesh
            name="COMPOUND001_8"
            geometry={nodes.COMPOUND001_8.geometry}
            material={materials.mat_14}
          />
          <mesh
            name="COMPOUND001_9"
            geometry={nodes.COMPOUND001_9.geometry}
            material={materials.mat_15}
          />
          <mesh
            name="COMPOUND001_10"
            geometry={nodes.COMPOUND001_10.geometry}
            material={materials.mat_16}
          />
          <mesh
            name="COMPOUND001_11"
            geometry={nodes.COMPOUND001_11.geometry}
            material={materials.mat_17}
          />
          <mesh
            name="COMPOUND001_12"
            geometry={nodes.COMPOUND001_12.geometry}
            material={materials.mat_18}
          />
          <mesh
            name="COMPOUND001_13"
            geometry={nodes.COMPOUND001_13.geometry}
            material={materials.mat_19}
          />
          <mesh
            name="COMPOUND001_14"
            geometry={nodes.COMPOUND001_14.geometry}
            material={materials.mat_20}
          />
          <mesh
            name="COMPOUND001_15"
            geometry={nodes.COMPOUND001_15.geometry}
            material={materials.mat_21}
          />
          <mesh
            name="COMPOUND001_16"
            geometry={nodes.COMPOUND001_16.geometry}
            material={materials.mat_22}
          />
          <mesh
            name="COMPOUND001_17"
            geometry={nodes.COMPOUND001_17.geometry}
            material={materials.mat_23}
          />
        </group>
        <group
          name="ws2812"
          position={[0.025, 0.008, 0.018]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
        >
          <mesh
            name="SOLID_1"
            geometry={nodes.SOLID_1.geometry}
            material={materials.mat_4}
          />
          <mesh
            name="SOLID_2"
            geometry={nodes.SOLID_2.geometry}
            material={materials.mat_5}
          />
          <mesh
            name="SOLID_3"
            geometry={nodes.SOLID_3.geometry}
            material={materials.mat_6}
          />
          <mesh
            name="SOLID_4"
            geometry={nodes.SOLID_4.geometry}
            material={materials.mat_7}
          />
          <mesh
            name="SOLID_5"
            geometry={nodes.SOLID_5.geometry}
            material={materials.mat_8}
          />
          <mesh
            name="SOLID_6"
            geometry={nodes.SOLID_6.geometry}
            material={materials.mat_9}
          />
        </group>
        <group
          name="ws2813"
          position={[0.101, 0.008, 0.018]}
          rotation={[Math.PI / 2, 0, 0]}
        >
          <mesh
            name="SOLID001_5"
            geometry={nodes.SOLID001_5.geometry}
            material={materials.mat_4}
          />
          <mesh
            name="SOLID001_6"
            geometry={nodes.SOLID001_6.geometry}
            material={materials.mat_5}
          />
          <mesh
            name="SOLID001_7"
            geometry={nodes.SOLID001_7.geometry}
            material={materials.mat_6}
          />
          <mesh
            name="SOLID001_8"
            geometry={nodes.SOLID001_8.geometry}
            material={materials.mat_7}
          />
          <mesh
            name="SOLID001_9"
            geometry={nodes.SOLID001_9.geometry}
            material={materials.mat_8}
          />
          <mesh
            name="SOLID001_10"
            geometry={nodes.SOLID001_10.geometry}
            material={materials.mat_9}
          />
        </group>
        <group
          name="ws2814"
          position={[0.063, 0.008, -0.007]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
        >
          <mesh
            name="SOLID002_3"
            geometry={nodes.SOLID002_3.geometry}
            material={materials.mat_4}
          />
          <mesh
            name="SOLID002_4"
            geometry={nodes.SOLID002_4.geometry}
            material={materials.mat_5}
          />
          <mesh
            name="SOLID002_5"
            geometry={nodes.SOLID002_5.geometry}
            material={materials.mat_6}
          />
          <mesh
            name="SOLID002_6"
            geometry={nodes.SOLID002_6.geometry}
            material={materials.mat_7}
          />
          <mesh
            name="SOLID002_7"
            geometry={nodes.SOLID002_7.geometry}
            material={materials.mat_8}
          />
          <mesh
            name="SOLID002_8"
            geometry={nodes.SOLID002_8.geometry}
            material={materials.mat_9}
          />
        </group>
        <group
          name="ws2815"
          position={[0.101, 0.008, -0.001]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
        >
          <mesh
            name="SOLID003_1"
            geometry={nodes.SOLID003_1.geometry}
            material={materials.mat_4}
          />
          <mesh
            name="SOLID003_2"
            geometry={nodes.SOLID003_2.geometry}
            material={materials.mat_5}
          />
          <mesh
            name="SOLID003_3"
            geometry={nodes.SOLID003_3.geometry}
            material={materials.mat_6}
          />
          <mesh
            name="SOLID003_4"
            geometry={nodes.SOLID003_4.geometry}
            material={materials.mat_7}
          />
          <mesh
            name="SOLID003_5"
            geometry={nodes.SOLID003_5.geometry}
            material={materials.mat_8}
          />
          <mesh
            name="SOLID003_6"
            geometry={nodes.SOLID003_6.geometry}
            material={materials.mat_9}
          />
        </group>
        <group
          name="ws2816"
          position={[0.082, 0.008, 0.016]}
          rotation={[Math.PI / 2, 0, 0]}
        >
          <mesh
            name="SOLID004_1"
            geometry={nodes.SOLID004_1.geometry}
            material={materials.mat_4}
          />
          <mesh
            name="SOLID004_2"
            geometry={nodes.SOLID004_2.geometry}
            material={materials.mat_5}
          />
          <mesh
            name="SOLID004_3"
            geometry={nodes.SOLID004_3.geometry}
            material={materials.mat_6}
          />
          <mesh
            name="SOLID004_4"
            geometry={nodes.SOLID004_4.geometry}
            material={materials.mat_7}
          />
          <mesh
            name="SOLID004_5"
            geometry={nodes.SOLID004_5.geometry}
            material={materials.mat_8}
          />
          <mesh
            name="SOLID004_6"
            geometry={nodes.SOLID004_6.geometry}
            material={materials.mat_9}
          />
        </group>
        <group
          name="ws2817"
          position={[0.044, 0.008, -0.005]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
        >
          <mesh
            name="SOLID005_1"
            geometry={nodes.SOLID005_1.geometry}
            material={materials.mat_4}
          />
          <mesh
            name="SOLID005_2"
            geometry={nodes.SOLID005_2.geometry}
            material={materials.mat_5}
          />
          <mesh
            name="SOLID005_3"
            geometry={nodes.SOLID005_3.geometry}
            material={materials.mat_6}
          />
          <mesh
            name="SOLID005_4"
            geometry={nodes.SOLID005_4.geometry}
            material={materials.mat_7}
          />
          <mesh
            name="SOLID005_5"
            geometry={nodes.SOLID005_5.geometry}
            material={materials.mat_8}
          />
          <mesh
            name="SOLID005_6"
            geometry={nodes.SOLID005_6.geometry}
            material={materials.mat_9}
          />
        </group>
        <group
          name="ws2818"
          position={[0.005, 0.008, 0.02]}
          rotation={[Math.PI / 2, 0, 0]}
        >
          <mesh
            name="SOLID006_1"
            geometry={nodes.SOLID006_1.geometry}
            material={materials.mat_4}
          />
          <mesh
            name="SOLID006_2"
            geometry={nodes.SOLID006_2.geometry}
            material={materials.mat_5}
          />
          <mesh
            name="SOLID006_3"
            geometry={nodes.SOLID006_3.geometry}
            material={materials.mat_6}
          />
          <mesh
            name="SOLID006_4"
            geometry={nodes.SOLID006_4.geometry}
            material={materials.mat_7}
          />
          <mesh
            name="SOLID006_5"
            geometry={nodes.SOLID006_5.geometry}
            material={materials.mat_8}
          />
          <mesh
            name="SOLID006_6"
            geometry={nodes.SOLID006_6.geometry}
            material={materials.mat_9}
          />
        </group>
        <group
          name="ws2819"
          position={[0.024, 0.008, -0.001]}
          rotation={[Math.PI / 2, 0, 0]}
        >
          <mesh
            name="SOLID007_1"
            geometry={nodes.SOLID007_1.geometry}
            material={materials.mat_4}
          />
          <mesh
            name="SOLID007_2"
            geometry={nodes.SOLID007_2.geometry}
            material={materials.mat_5}
          />
          <mesh
            name="SOLID007_3"
            geometry={nodes.SOLID007_3.geometry}
            material={materials.mat_6}
          />
          <mesh
            name="SOLID007_4"
            geometry={nodes.SOLID007_4.geometry}
            material={materials.mat_7}
          />
          <mesh
            name="SOLID007_5"
            geometry={nodes.SOLID007_5.geometry}
            material={materials.mat_8}
          />
          <mesh
            name="SOLID007_6"
            geometry={nodes.SOLID007_6.geometry}
            material={materials.mat_9}
          />
        </group>
        <group
          name="ws2820"
          position={[0.093, 0.008, 0.056]}
          rotation={[Math.PI / 2, 0, 0.087]}
        >
          <mesh
            name="SOLID008_1"
            geometry={nodes.SOLID008_1.geometry}
            material={materials.mat_4}
          />
          <mesh
            name="SOLID008_2"
            geometry={nodes.SOLID008_2.geometry}
            material={materials.mat_5}
          />
          <mesh
            name="SOLID008_3"
            geometry={nodes.SOLID008_3.geometry}
            material={materials.mat_6}
          />
          <mesh
            name="SOLID008_4"
            geometry={nodes.SOLID008_4.geometry}
            material={materials.mat_7}
          />
          <mesh
            name="SOLID008_5"
            geometry={nodes.SOLID008_5.geometry}
            material={materials.mat_8}
          />
          <mesh
            name="SOLID008_6"
            geometry={nodes.SOLID008_6.geometry}
            material={materials.mat_9}
          />
        </group>
        <group
          name="ws2821"
          position={[0.073, 0.008, 0.053]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
        >
          <mesh
            name="SOLID009_1"
            geometry={nodes.SOLID009_1.geometry}
            material={materials.mat_4}
          />
          <mesh
            name="SOLID009_2"
            geometry={nodes.SOLID009_2.geometry}
            material={materials.mat_5}
          />
          <mesh
            name="SOLID009_3"
            geometry={nodes.SOLID009_3.geometry}
            material={materials.mat_6}
          />
          <mesh
            name="SOLID009_4"
            geometry={nodes.SOLID009_4.geometry}
            material={materials.mat_7}
          />
          <mesh
            name="SOLID009_5"
            geometry={nodes.SOLID009_5.geometry}
            material={materials.mat_8}
          />
          <mesh
            name="SOLID009_6"
            geometry={nodes.SOLID009_6.geometry}
            material={materials.mat_9}
          />
        </group>
        <group
          name="ws2822"
          position={[0.043, 0.008, 0.014]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
        >
          <mesh
            name="SOLID010_1"
            geometry={nodes.SOLID010_1.geometry}
            material={materials.mat_4}
          />
          <mesh
            name="SOLID010_2"
            geometry={nodes.SOLID010_2.geometry}
            material={materials.mat_5}
          />
          <mesh
            name="SOLID010_3"
            geometry={nodes.SOLID010_3.geometry}
            material={materials.mat_6}
          />
          <mesh
            name="SOLID010_4"
            geometry={nodes.SOLID010_4.geometry}
            material={materials.mat_7}
          />
          <mesh
            name="SOLID010_5"
            geometry={nodes.SOLID010_5.geometry}
            material={materials.mat_8}
          />
          <mesh
            name="SOLID010_6"
            geometry={nodes.SOLID010_6.geometry}
            material={materials.mat_9}
          />
        </group>
        <group
          name="ws2823"
          position={[0.025, 0.008, 0.037]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
        >
          <mesh
            name="SOLID011_1"
            geometry={nodes.SOLID011_1.geometry}
            material={materials.mat_4}
          />
          <mesh
            name="SOLID011_2"
            geometry={nodes.SOLID011_2.geometry}
            material={materials.mat_5}
          />
          <mesh
            name="SOLID011_3"
            geometry={nodes.SOLID011_3.geometry}
            material={materials.mat_6}
          />
          <mesh
            name="SOLID011_4"
            geometry={nodes.SOLID011_4.geometry}
            material={materials.mat_7}
          />
          <mesh
            name="SOLID011_5"
            geometry={nodes.SOLID011_5.geometry}
            material={materials.mat_8}
          />
          <mesh
            name="SOLID011_6"
            geometry={nodes.SOLID011_6.geometry}
            material={materials.mat_9}
          />
        </group>
        <group
          name="ws2824"
          position={[0.082, 0.008, -0.003]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
        >
          <mesh
            name="SOLID012_1"
            geometry={nodes.SOLID012_1.geometry}
            material={materials.mat_4}
          />
          <mesh
            name="SOLID012_2"
            geometry={nodes.SOLID012_2.geometry}
            material={materials.mat_5}
          />
          <mesh
            name="SOLID012_3"
            geometry={nodes.SOLID012_3.geometry}
            material={materials.mat_6}
          />
          <mesh
            name="SOLID012_4"
            geometry={nodes.SOLID012_4.geometry}
            material={materials.mat_7}
          />
          <mesh
            name="SOLID012_5"
            geometry={nodes.SOLID012_5.geometry}
            material={materials.mat_8}
          />
          <mesh
            name="SOLID012_6"
            geometry={nodes.SOLID012_6.geometry}
            material={materials.mat_9}
          />
        </group>
        <group
          name="ws2825"
          position={[0.006, 0.008, 0.039]}
          rotation={[Math.PI / 2, 0, 0]}
        >
          <mesh
            name="SOLID013_1"
            geometry={nodes.SOLID013_1.geometry}
            material={materials.mat_4}
          />
          <mesh
            name="SOLID013_2"
            geometry={nodes.SOLID013_2.geometry}
            material={materials.mat_5}
          />
          <mesh
            name="SOLID013_3"
            geometry={nodes.SOLID013_3.geometry}
            material={materials.mat_6}
          />
          <mesh
            name="SOLID013_4"
            geometry={nodes.SOLID013_4.geometry}
            material={materials.mat_7}
          />
          <mesh
            name="SOLID013_5"
            geometry={nodes.SOLID013_5.geometry}
            material={materials.mat_8}
          />
          <mesh
            name="SOLID013_6"
            geometry={nodes.SOLID013_6.geometry}
            material={materials.mat_9}
          />
        </group>
        <group
          name="ws2826"
          position={[0.082, 0.008, 0.035]}
          rotation={[Math.PI / 2, 0, 0]}
        >
          <mesh
            name="SOLID014_1"
            geometry={nodes.SOLID014_1.geometry}
            material={materials.mat_4}
          />
          <mesh
            name="SOLID014_2"
            geometry={nodes.SOLID014_2.geometry}
            material={materials.mat_5}
          />
          <mesh
            name="SOLID014_3"
            geometry={nodes.SOLID014_3.geometry}
            material={materials.mat_6}
          />
          <mesh
            name="SOLID014_4"
            geometry={nodes.SOLID014_4.geometry}
            material={materials.mat_7}
          />
          <mesh
            name="SOLID014_5"
            geometry={nodes.SOLID014_5.geometry}
            material={materials.mat_8}
          />
          <mesh
            name="SOLID014_6"
            geometry={nodes.SOLID014_6.geometry}
            material={materials.mat_9}
          />
        </group>
        <group
          name="ws2827"
          position={[0.114, 0.008, 0.063]}
          rotation={[Math.PI / 2, 0, 0.262]}
        >
          <mesh
            name="SOLID015_1"
            geometry={nodes.SOLID015_1.geometry}
            material={materials.mat_4}
          />
          <mesh
            name="SOLID015_2"
            geometry={nodes.SOLID015_2.geometry}
            material={materials.mat_5}
          />
          <mesh
            name="SOLID015_3"
            geometry={nodes.SOLID015_3.geometry}
            material={materials.mat_6}
          />
          <mesh
            name="SOLID015_4"
            geometry={nodes.SOLID015_4.geometry}
            material={materials.mat_7}
          />
          <mesh
            name="SOLID015_5"
            geometry={nodes.SOLID015_5.geometry}
            material={materials.mat_8}
          />
          <mesh
            name="SOLID015_6"
            geometry={nodes.SOLID015_6.geometry}
            material={materials.mat_9}
          />
        </group>
        <group
          name="ws2828"
          position={[0.1, 0.008, 0.037]}
          rotation={[Math.PI / 2, 0, 0]}
        >
          <mesh
            name="SOLID016_1"
            geometry={nodes.SOLID016_1.geometry}
            material={materials.mat_4}
          />
          <mesh
            name="SOLID016_2"
            geometry={nodes.SOLID016_2.geometry}
            material={materials.mat_5}
          />
          <mesh
            name="SOLID016_3"
            geometry={nodes.SOLID016_3.geometry}
            material={materials.mat_6}
          />
          <mesh
            name="SOLID016_4"
            geometry={nodes.SOLID016_4.geometry}
            material={materials.mat_7}
          />
          <mesh
            name="SOLID016_5"
            geometry={nodes.SOLID016_5.geometry}
            material={materials.mat_8}
          />
          <mesh
            name="SOLID016_6"
            geometry={nodes.SOLID016_6.geometry}
            material={materials.mat_9}
          />
        </group>
        <group
          name="ws2829"
          position={[0.063, 0.008, 0.012]}
          rotation={[Math.PI / 2, 0, 0]}
        >
          <mesh
            name="SOLID017_1"
            geometry={nodes.SOLID017_1.geometry}
            material={materials.mat_4}
          />
          <mesh
            name="SOLID017_2"
            geometry={nodes.SOLID017_2.geometry}
            material={materials.mat_5}
          />
          <mesh
            name="SOLID017_3"
            geometry={nodes.SOLID017_3.geometry}
            material={materials.mat_6}
          />
          <mesh
            name="SOLID017_4"
            geometry={nodes.SOLID017_4.geometry}
            material={materials.mat_7}
          />
          <mesh
            name="SOLID017_5"
            geometry={nodes.SOLID017_5.geometry}
            material={materials.mat_8}
          />
          <mesh
            name="SOLID017_6"
            geometry={nodes.SOLID017_6.geometry}
            material={materials.mat_9}
          />
        </group>
        <group
          name="ws2830"
          position={[0.063, 0.008, 0.031]}
          rotation={[Math.PI / 2, 0, 0]}
        >
          <mesh
            name="SOLID018_1"
            geometry={nodes.SOLID018_1.geometry}
            material={materials.mat_4}
          />
          <mesh
            name="SOLID018_2"
            geometry={nodes.SOLID018_2.geometry}
            material={materials.mat_5}
          />
          <mesh
            name="SOLID018_3"
            geometry={nodes.SOLID018_3.geometry}
            material={materials.mat_6}
          />
          <mesh
            name="SOLID018_4"
            geometry={nodes.SOLID018_4.geometry}
            material={materials.mat_7}
          />
          <mesh
            name="SOLID018_5"
            geometry={nodes.SOLID018_5.geometry}
            material={materials.mat_8}
          />
          <mesh
            name="SOLID018_6"
            geometry={nodes.SOLID018_6.geometry}
            material={materials.mat_9}
          />
        </group>
        <group
          name="ws2831"
          position={[0.044, 0.008, 0.034]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
        >
          <mesh
            name="SOLID019_1"
            geometry={nodes.SOLID019_1.geometry}
            material={materials.mat_4}
          />
          <mesh
            name="SOLID019_2"
            geometry={nodes.SOLID019_2.geometry}
            material={materials.mat_5}
          />
          <mesh
            name="SOLID019_3"
            geometry={nodes.SOLID019_3.geometry}
            material={materials.mat_6}
          />
          <mesh
            name="SOLID019_4"
            geometry={nodes.SOLID019_4.geometry}
            material={materials.mat_7}
          />
          <mesh
            name="SOLID019_5"
            geometry={nodes.SOLID019_5.geometry}
            material={materials.mat_8}
          />
          <mesh
            name="SOLID019_6"
            geometry={nodes.SOLID019_6.geometry}
            material={materials.mat_9}
          />
        </group>
        <group
          name="ws2832"
          position={[0.005, 0.008, 0.001]}
          rotation={[Math.PI / 2, 0, 0]}
        >
          <mesh
            name="SOLID020_1"
            geometry={nodes.SOLID020_1.geometry}
            material={materials.mat_4}
          />
          <mesh
            name="SOLID020_2"
            geometry={nodes.SOLID020_2.geometry}
            material={materials.mat_5}
          />
          <mesh
            name="SOLID020_3"
            geometry={nodes.SOLID020_3.geometry}
            material={materials.mat_6}
          />
          <mesh
            name="SOLID020_4"
            geometry={nodes.SOLID020_4.geometry}
            material={materials.mat_7}
          />
          <mesh
            name="SOLID020_5"
            geometry={nodes.SOLID020_5.geometry}
            material={materials.mat_8}
          />
          <mesh
            name="SOLID020_6"
            geometry={nodes.SOLID020_6.geometry}
            material={materials.mat_9}
          />
        </group>
        <mesh
          name="v1_PCB"
          geometry={nodes.v1_PCB.geometry}
          material={materials.mat_24}
        />
        <mesh
          name="SOLID002"
          geometry={nodes.SOLID002.geometry}
          material={materials.mat_3}
          position={[0.079, -0.003, -0.003]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <PerspectiveCamera
        name="Camera"
        makeDefault={true}
        far={100}
        near={0.1}
        fov={22.895}
        position={[0.065, 0.255, 0.333]}
        rotation={[-0.642, 0, 0]}
      />
      {/* <spotLight */}
      {/*   name="Spot" */}
      {/*   intensity={543.514} */}
      {/*   angle={Math.PI / 8} */}
      {/*   penumbra={0.15} */}
      {/*   decay={2} */}
      {/*   position={[0.077, 0.213, 0.089]} */}
      {/*   rotation={[-1.051, 0.286, -0.16]} */}
      {/* /> */}
      {/* <spotLight */}
      {/*   name="Spot001" */}
      {/*   intensity={543.514} */}
      {/*   angle={Math.PI / 8} */}
      {/*   penumbra={0.15} */}
      {/*   decay={2} */}
      {/*   position={[0.077, 0.088, 0.217]} */}
      {/*   rotation={[-0.386, 0.286, -0.16]} */}
      {/* /> */}
      {/* <spotLight */}
      {/*   name="Spot002" */}
      {/*   intensity={543.514} */}
      {/*   angle={Math.PI / 8} */}
      {/*   penumbra={0.15} */}
      {/*   decay={2} */}
      {/*   position={[-0.01, 0.247, 0]} */}
      {/*   rotation={[-Math.PI / 2, 0, 0]} */}
      {/* /> */}
      {/* <spotLight */}
      {/*   name="Spot003" */}
      {/*   intensity={543.514} */}
      {/*   angle={Math.PI / 8} */}
      {/*   penumbra={0.15} */}
      {/*   decay={2} */}
      {/*   position={[0.188, 0.148, -0.22]} */}
      {/*   rotation={[-2.529, 0.366, 0.471]} */}
      {/* /> */}
      <mesh
        name="case-top"
        geometry={nodes["case-top"].geometry}
        material={materials.plate}
      />
      <mesh
        name="keycap001"
        geometry={nodes.keycap001.geometry}
        material={materials.plate}
        position={[0, 0.014, 0.001]}
      />
      <mesh
        name="keycap002"
        geometry={nodes.keycap002.geometry}
        material={materials.plate}
        position={[0.019, 0.014, 0.005]}
      />
      <mesh
        name="keycap003"
        geometry={nodes.keycap003.geometry}
        material={materials.plate}
        position={[0.038, 0.014, 0.007]}
      />
      <mesh
        name="keycap004"
        geometry={nodes.keycap004.geometry}
        material={materials.plate}
        position={[-0.019, 0.014, 0.003]}
      />
      <mesh
        name="keycap005"
        geometry={nodes.keycap005.geometry}
        material={materials.plate}
        position={[-0.039, 0.014, 0.007]}
      />
      <mesh
        name="keycap006"
        geometry={nodes.keycap006.geometry}
        material={materials.plate}
        position={[-0.058, 0.014, 0.009]}
      />
      <mesh
        name="keycap007"
        geometry={nodes.keycap007.geometry}
        material={materials.plate}
        position={[0, 0.014, -0.018]}
      />
      <mesh
        name="keycap008"
        geometry={nodes.keycap008.geometry}
        material={materials.plate}
        position={[0.019, 0.014, -0.014]}
      />
      <mesh
        name="keycap009"
        geometry={nodes.keycap009.geometry}
        material={materials.plate}
        position={[0.038, 0.014, -0.012]}
      />
      <mesh
        name="keycap010"
        geometry={nodes.keycap010.geometry}
        material={materials.plate}
        position={[-0.019, 0.014, -0.016]}
      />
      <mesh
        name="keycap011"
        geometry={nodes.keycap011.geometry}
        material={materials.plate}
        position={[-0.039, 0.014, -0.012]}
      />
      <mesh
        name="keycap012"
        geometry={nodes.keycap012.geometry}
        material={materials.plate}
        position={[-0.058, 0.014, -0.01]}
      />
      <mesh
        name="keycap013"
        geometry={nodes.keycap013.geometry}
        material={materials.plate}
        position={[0, 0.014, -0.038]}
      />
      <mesh
        name="keycap014"
        geometry={nodes.keycap014.geometry}
        material={materials.plate}
        position={[0.019, 0.014, -0.034]}
      />
      <mesh
        name="keycap015"
        geometry={nodes.keycap015.geometry}
        material={materials.plate}
        position={[0.038, 0.014, -0.032]}
      />
      <mesh
        name="keycap016"
        geometry={nodes.keycap016.geometry}
        material={materials.plate}
        position={[-0.019, 0.014, -0.036]}
      />
      <mesh
        name="keycap017"
        geometry={nodes.keycap017.geometry}
        material={materials.plate}
        position={[-0.039, 0.014, -0.032]}
      />
      <mesh
        name="keycap018"
        geometry={nodes.keycap018.geometry}
        material={materials.plate}
        position={[-0.058, 0.014, -0.03]}
      />
      <mesh
        name="keycap019"
        geometry={nodes.keycap019.geometry}
        material={materials.plate}
        position={[0.01, 0.014, 0.023]}
      />
      <mesh
        name="keycap020"
        geometry={nodes.keycap020.geometry}
        material={materials.plate}
        position={[0.03, 0.014, 0.025]}
        rotation={[0, -0.087, 0]}
      />
      <mesh
        name="keycap"
        geometry={nodes.keycap.geometry}
        material={materials.plate}
        position={[0.05, 0.014, 0.032]}
        rotation={[0, -0.262, 0]}
      />
    </group>
  );
}

useGLTF.preload("/ks1-model.glb");
